### ISSUE TITLE
Interfaces are not exported

### ISSUE THREAD

**Issue by beshur** [Alibriaan/liqpay-sdk-tool#1]
Hi!

Interfaces are not exported, so it's pretty hard to use this in a typed environment.

<img width="1650" alt="Screenshot 2023-07-10 at 01 04 53" src="https://github.com/Alibriaan/liqpay-sdk-tool/assets/532273/155a54b3-aaee-4f48-8bd9-220f7feb80fb">

**Comment by beshur** [comment]
Nevermind, I managed to import it directly. Was it intentional?
```
import {
  LiqPayActionsEnum,
  LiqPayData,
} from 'liqpay-sdk-tool/build/interfaces/liq-pay.interfaces'
```

**Comment by Alibriaan** [comment]
Hello, sorry it's so late, It was not intentional, i'll release patch release today
